### ISSUE TITLE
probleme at deletion

### ISSUE THREAD

**Issue by sinsunsan** [jraede/cascading-relations#1]
Hello, 

I've installed and used your plugin successfully, 
but I have problem at deletion with a mean type express app 
http://mean.io/#!/

It say it don't know the model of the refs. 
But the strange thing is that it does not have any problem for update query. 
I had the idea, that it's you automated child document deletion stuff that cause the problem, though I am not sure. 

What you opinion ? where to find for debugging ?

/SEB/www/bricks/mean/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (/SEB/www/bricks/mean/node_modules/cascading-relations/node_modules/mongoose/lib/index.js:323:13)
    at model.schema.methods.$__handleDeletionOfDoc (/SEB/www/bricks/mean/node_modules/cascading-relations/index.js:378:27)
    at model.schema.methods.$__handleDeletionAtSingleRelationPath (/SEB/www/bricks/mean/node_modules/cascading-relations/index.js:361:17)
    at model.schema.methods.$__handleDeletion (/SEB/www/bricks/mean/node_modules/cascading-relations/index.js:351:19)
    at model.<anonymous> (/SEB/www/bricks/mean/node_modules/cascading-relations/index.js:400:26)
    at model.EventEmitter.emit (events.js:95:17)
    at /SEB/www/bricks/mean/node_modules/mongoose/lib/model.js:583:10
    at /SEB/www/bricks/mean/node_modules/mongoose/lib/utils.js:408:16
    at /SEB/www/bricks/mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:400:9
    at Server.Base._callHandler (/SEB/www/bricks/mean/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
6 Nov 02:49:11 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by jraede** [comment]
Hi, sorry it took so long to get back to you. Do you have a cascade config to a collection ("User") that hasn't been registered yet? You need to register a mongoose model for each related document as well.

**Comment by sinsunsan** [comment]
Thanks any way. 
I need to configure all the mongoose model that use cascading relation ? Not the one that do not have usage of it ? 
Indeed per aps I have forgotten to configure user which is loaded in all models. 
I will hav a look and get back to you.
